name: Docker Image CI

on:
  push:
    branches: [ "main" ]
#    tags:
#      - "v*.*.*"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3



    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          name/app
          ghcr.io/username/app
        # generate Docker tags based on the following events/attributes
        tags: |
          # type=ref,event=branch
          type=ref,event=pr
#          type=semver,pattern={{version}}
#          type=semver,pattern={{major}}.{{minor}}
#          type=semver,pattern={{major}}
          type=sha

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag ghcr.io/e-gugliotti-noaa/ss3-docker:latest
        
    #- name: Push the Docker image
      #run: docker push ghcr.io/e-gugliotti-noaa/ss3-docker:latest
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
